### ISSUE TITLE
Is it possible to disable drawableRight for pickers?

### ISSUE THREAD

**Issue by demogorgorn** [marvinlabs/android-floatinglabel-widgets#37] opened 2015-07-01 12:51 UTC
Is it possible to programmatically disable drawableLeft for pickers? This is because there is no possibility to adjust heights of Fl...EditText and FL..Picker which are placed in one row (horizontal Linearlayout) because of drawableRight...

**Comment by demogorgorn** [comment] 2015-07-01 13:46
Here is screenshot
![unaligned](https://cloud.githubusercontent.com/assets/7351565/8455933/c4c48f0c-2010-11e5-80ba-fae8ec21453a.png)
:

**Comment by vpratfr** [comment] 2015-07-01 15:06
This is a duplicate of #16. Closing this one in favor of the other. Thanks.

**Closed by vpratfr** 2015-07-01 15:06 UTC
